import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category',
      label: 'Account Setup',
      items: [{type: 'autogenerated', dirName: 'account-setup'}],
    },
    {
      type: 'category',
      label: 'Leads',
      items: [{type: 'autogenerated', dirName: 'leads'}],
    },
    {
      type: 'category',
      label: 'Jobs',
      items: [{type: 'autogenerated', dirName: 'jobs'}],
    },
    {
      type: 'category',
      label: 'Quotes',
      items: [{type: 'autogenerated', dirName: 'quotes'}],
    },
    {
      type: 'category',
      label: 'Packages',
      items: [{type: 'autogenerated', dirName: 'packages'}],
    },
    {
      type: 'category',
      label: 'Contracts',
      items: [{type: 'autogenerated', dirName: 'contracts'}],
    },
    {
      type: 'category',
      label: 'Invoices',
      items: [{type: 'autogenerated', dirName: 'invoices'}],
    },
    {
      type: 'category',
      label: 'Clients',
      items: [{type: 'autogenerated', dirName: 'clients'}],
    },
    {
      type: 'category',
      label: 'Client Portal',
      items: [{type: 'autogenerated', dirName: 'client-portal'}],
    },
    {
      type: 'category',
      label: 'Calendar',
      items: [{type: 'autogenerated', dirName: 'calendar'}],
    },
    {
      type: 'category',
      label: 'Mini Sessions',
      items: [{type: 'autogenerated', dirName: 'mini-sessions'}],
    },
    {
      type: 'category',
      label: 'Galleries',
      items: [{type: 'autogenerated', dirName: 'galleries'}],
    },
    {
      type: 'category',
      label: 'Workflows',
      items: [{type: 'autogenerated', dirName: 'workflows'}],
    },
    {
      type: 'category',
      label: 'Email Templates',
      items: [{type: 'autogenerated', dirName: 'email-templates'}],
    },
    {
      type: 'category',
      label: 'Questionnaires',
      items: [{type: 'autogenerated', dirName: 'questionnaires'}],
    },
    {
      type: 'category',
      label: 'Team',
      items: [{type: 'autogenerated', dirName: 'team'}],
    },
    {
      type: 'category',
      label: 'Reports',
      items: [{type: 'autogenerated', dirName: 'reports'}],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [{type: 'autogenerated', dirName: 'integrations'}],
    },
    {
      type: 'category',
      label: 'Mobile',
      items: [{type: 'autogenerated', dirName: 'mobile'}],
    },
    {
      type: 'category',
      label: 'Billing',
      items: [{type: 'autogenerated', dirName: 'billing'}],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      items: [{type: 'autogenerated', dirName: 'troubleshooting'}],
    },
    'glossary',
  ],
};

export default sidebars;
